### ISSUE TITLE
[Feature Request] Adding c & s & a & sp

### ISSUE THREAD

**Issue by TechnicJelle** [MCMainiac/GameModeControl#11]
I've always used the first letter(s) for changing gamemodes, but this plugin doesn't allow those.
I've found a (temporary?) way around it using an alias plugin. Could you add this functionality?

**Comment by ricardoboss** [comment]
This should be an easy task. I'm even thinking of adding a dynamic way to add/remove commands in the config itself. That way, you could modify all commands and what they do. Sound good?

**Comment by ricardoboss** [comment]
@ggblbl I'm afraid that adding those commands (namely /s, /c, /a, /sp) could clash with some other plugins. I'd rather not add those.
